[package]
name = "obs-sys"
version = "0.1.2"
authors = ["Bennett Hardwick <me@bennetthardwick.com>"]
edition = "2018"
description = "Bindgen of <obs/obs.h>"
license = "GPL-2.0"

[build-dependencies]
bindgen = "0.53.1"